  name: DemoApp Release

  on:
    push:
      branches: [ main ]

  jobs:
      version:
        name: Create version number
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Fetch all history for all tags and branches
            run: |
              git config remote.origin.url https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}
              git fetch --prune --depth=10000
          - name: Install GitVersion
            uses: gittools/actions/gitversion/setup@v1.0.0
            with:
              versionSpec: '5.x'
          - name: Use GitVersion
            id: gitversion
            uses: gittools/actions/gitversion/execute@v1.0.0
          - name: Create version.txt with nuGetVersion
            run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
          - name: Upload version.txt
            uses: actions/upload-artifact@v4
            with:
              name: gitversion
              path: version.txt

      release:
        name: Release app to internal track
        needs: [ build ]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Get appbundle from artifacts
            uses: actions/download-artifact@v4
            with:
              name: appbundle
          - name: Release app to internal track
            uses: r0adkll/upload-google-play@v1
            with:
              serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
              packageName: com.flutterworkflow
              releaseFiles: app-release.aab
              track: internal